import { useState, useCallback, useEffect } from "react";

const TRAINING_BOTS = ["GPTBot","ClaudeBot","CCBot","Google-Extended","FacebookBot","Bytespider","Diffbot","Omgilibot","Amazonbot","cohere-ai","AI2Bot","Applebot-Extended"];
const AI_INPUT_BOTS = ["ChatGPT-User","Claude-User"];

const DEFAULT_MANIFEST = `{
  "version": "0.1",
  "publisher": {
    "name": "My Blog",
    "contact": "mailto:me@example.com"
  },
  "defaults": {
    "standard": {
      "train-ai": { "state": "deny" },
      "search": { "state": "allow" }
    },
    "experimental": {
      "train-genai": { "state": "deny" },
      "ai-input": { "state": "deny" }
    }
  }
}`;

function getState(policies, cat) {
  const v = policies?.[cat];
  if (v && typeof v === "object") return v.state || "unknown";
  return "unknown";
}

function getDefaultState(manifest, cat) {
  const d = manifest?.defaults || {};
  let s = getState(d.standard, cat);
  if (s === "unknown") s = getState(d.experimental, cat);
  return s;
}

function lower(state, fb) {
  if (state === "allow" || state === "deny") return state;
  if (state === "unknown") return null;
  return fb || "deny";
}

function compile(manifest) {
  if (!manifest || !manifest.version) return { error: "Invalid manifest" };
  const fb = manifest.defaults?.fallbacks?.unexpressible_state || "deny";
  const trainState = getDefaultState(manifest, "train-ai");
  const trainGenaiState = getDefaultState(manifest, "train-genai");
  const searchState = getDefaultState(manifest, "search");
  const aiInputState = getDefaultState(manifest, "ai-input");
  const blockTraining = lower(trainState, fb) === "deny" || lower(trainGenaiState, fb) === "deny";
  const blockAiInput = lower(aiInputState, fb) === "deny";

  // robots.txt
  const r = ["# robots.txt", "# Generated by consent.txt compiler v0.1", `# Publisher: ${manifest.publisher?.name || "Unknown"}`, "", "User-Agent: *", "Allow: /", ""];
  if (blockTraining) {
    TRAINING_BOTS.forEach(b => r.push(`User-Agent: ${b}`));
    r.push("Disallow: /", "");
  }
  if (blockAiInput) {
    AI_INPUT_BOTS.forEach(b => r.push(`User-Agent: ${b}`));
    r.push("Disallow: /", "");
  }
  if (manifest.publisher?.url) r.push(`Sitemap: ${manifest.publisher.url.replace(/\/$/,"")}/sitemap.xml`, "");

  // AIPREF — only standardized categories
  const aiprefParts = [];
  const stdOnly = manifest.defaults?.standard || {};
  for (const cat of ["train-ai", "search"]) {
    const s = getState(stdOnly, cat);
    const l = lower(s, fb);
    if (l === "allow") aiprefParts.push(`${cat}=y`);
    else if (l === "deny") aiprefParts.push(`${cat}=n`);
  }
  const aipref = aiprefParts.length ? `Content-Usage: ${aiprefParts.join(", ")}` : "# No AIPREF preferences to emit";

  // X-Robots-Tag
  const xTags = [];
  if (lower(searchState, fb) === "deny") {
    xTags.push("X-Robots-Tag: noindex, nofollow");
  } else {
    const merged = { ...(manifest.defaults?.experimental || {}), ...(manifest.defaults?.standard || {}) };
    const aiInput = merged["ai-input"];
    if (aiInput?.conditions?.max_excerpt_chars) xTags.push(`X-Robots-Tag: max-snippet:${aiInput.conditions.max_excerpt_chars}`);
    if (blockTraining) xTags.push("X-Robots-Tag: googlebot: noai, noimageai");
  }

  // Google-Extended
  let gext = "";
  if (blockTraining) gext = "User-Agent: Google-Extended\nDisallow: /";

  // TDMRep
  const tdmUrl = manifest.endpoints?.tdm_policy;
  const tdm = tdmUrl ? `Link: <${tdmUrl}>; rel="tdm-policy"` : "# No TDMRep endpoint configured";

  // Validation
  const issues = [];
  if (!manifest.publisher?.name) issues.push("Missing publisher.name");
  if (!manifest.publisher?.contact) issues.push("Missing publisher.contact");
  if (!manifest.defaults) issues.push("Missing defaults block");
  const hasRich = [trainState, trainGenaiState, searchState, aiInputState].some(s => s === "charge" || s === "conditional");
  if (hasRich && !manifest.defaults?.fallbacks) issues.push("charge/conditional states without fallbacks defined");

  return {
    robotsTxt: r.join("\n"),
    aipref,
    xRobotsTag: xTags.length ? xTags.join("\n") : "# No preview directives needed",
    googleExtended: gext || "# Google-Extended not blocked",
    tdmrep: tdm,
    issues,
    stats: {
      trainingBlocked: blockTraining ? TRAINING_BOTS.length : 0,
      aiInputBlocked: blockAiInput ? AI_INPUT_BOTS.length : 0,
      totalBots: TRAINING_BOTS.length + AI_INPUT_BOTS.length,
    }
  };
}

const TABS = [
  { id: "robots", label: "robots.txt", key: "robotsTxt" },
  { id: "aipref", label: "AIPREF header", key: "aipref" },
  { id: "xrobots", label: "X-Robots-Tag", key: "xRobotsTag" },
  { id: "gext", label: "Google-Extended", key: "googleExtended" },
  { id: "tdm", label: "TDMRep", key: "tdmrep" },
];

const PRESETS = {
  minimal: DEFAULT_MANIFEST,
  "news-publisher": JSON.stringify({
    version: "0.1",
    publisher: { name: "Example News", url: "https://news.example.com", contact: "mailto:ai@news.example.com", jurisdictions: ["US","EU"] },
    defaults: {
      fallbacks: { unexpressible_state: "deny", unknown_identity: "deny" },
      standard: { "train-ai": { state: "deny" }, search: { state: "allow" } },
      experimental: { "train-genai": { state: "deny" }, "ai-input": { state: "conditional", conditions: { identity: "signed", citation_required: true, max_excerpt_chars: 160 } } }
    },
    endpoints: { payment: "https://news.example.com/.well-known/ai-payment", tdm_policy: "https://news.example.com/.well-known/tdmrep.json" },
    interop: { emit: ["robots-txt","aipref-header","x-robots-tag","google-extended","tdmrep"] }
  }, null, 2),
  "open-access": JSON.stringify({
    version: "0.1",
    publisher: { name: "Open Research Lab", contact: "mailto:data@openlab.edu" },
    defaults: {
      fallbacks: { unexpressible_state: "allow", unknown_identity: "allow" },
      standard: { "train-ai": { state: "allow" }, search: { state: "allow" } },
      experimental: { "train-genai": { state: "allow" }, "ai-input": { state: "allow" }, embedding: { state: "allow" } }
    }
  }, null, 2),
  lockdown: JSON.stringify({
    version: "0.1",
    publisher: { name: "Fortress Corp", contact: "mailto:legal@fortress.io" },
    defaults: {
      fallbacks: { unexpressible_state: "deny", unknown_identity: "deny" },
      standard: { "train-ai": { state: "deny" }, search: { state: "deny" } },
      experimental: { "train-genai": { state: "deny" }, "ai-input": { state: "deny" }, "agentic-access": { state: "deny" }, transform: { state: "deny" }, "generate-media": { state: "deny" }, embedding: { state: "deny" } }
    }
  }, null, 2),
};

export default function Playground() {
  const [input, setInput] = useState(DEFAULT_MANIFEST);
  const [activeTab, setActiveTab] = useState("robots");
  const [result, setResult] = useState(null);
  const [parseError, setParseError] = useState(null);

  const recompile = useCallback((text) => {
    try {
      const m = JSON.parse(text);
      setParseError(null);
      setResult(compile(m));
    } catch (e) {
      setParseError(e.message);
      setResult(null);
    }
  }, []);

  useEffect(() => { recompile(input); }, []);

  const handleInput = (val) => {
    setInput(val);
    recompile(val);
  };

  const activeOutput = result ? result[TABS.find(t => t.id === activeTab)?.key] : "";
  const lineCount = activeOutput ? activeOutput.split("\n").length : 0;

  return (
    <div style={{ fontFamily: "'IBM Plex Mono', 'Fira Code', 'SF Mono', monospace", fontSize: 13 }}>
      <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet" />

      <div style={{ display: "flex", gap: 6, marginBottom: 12, flexWrap: "wrap" }}>
        {Object.keys(PRESETS).map(p => (
          <button key={p} onClick={() => handleInput(PRESETS[p])} style={{ fontSize: 11, padding: "4px 10px", background: "var(--color-background-secondary)", border: "0.5px solid var(--color-border-tertiary)", borderRadius: 4, color: "var(--color-text-secondary)", cursor: "pointer" }}>
            {p}
          </button>
        ))}
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, minHeight: 380 }}>
        {/* Input */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ fontSize: 11, fontWeight: 500, color: "var(--color-text-tertiary)", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 6, display: "flex", justifyContent: "space-between" }}>
            <span>Manifest</span>
            {parseError && <span style={{ color: "var(--color-text-danger)", textTransform: "none", letterSpacing: 0 }}>{parseError.slice(0, 50)}</span>}
          </div>
          <textarea
            value={input}
            onChange={e => handleInput(e.target.value)}
            spellCheck={false}
            style={{
              flex: 1, resize: "none", fontFamily: "inherit", fontSize: 12, lineHeight: 1.6,
              padding: 12, background: "var(--color-background-secondary)", color: "var(--color-text-primary)",
              border: parseError ? "1px solid var(--color-border-danger)" : "0.5px solid var(--color-border-tertiary)",
              borderRadius: "var(--border-radius-md)", outline: "none", tabSize: 2, minHeight: 340,
            }}
          />
        </div>

        {/* Output */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", gap: 1, marginBottom: 6, flexWrap: "wrap" }}>
            {TABS.map(t => (
              <button key={t.id} onClick={() => setActiveTab(t.id)} style={{
                fontSize: 11, fontWeight: activeTab === t.id ? 500 : 400, padding: "4px 8px",
                background: activeTab === t.id ? "var(--color-background-primary)" : "transparent",
                border: activeTab === t.id ? "0.5px solid var(--color-border-tertiary)" : "0.5px solid transparent",
                borderRadius: "4px 4px 0 0", cursor: "pointer",
                color: activeTab === t.id ? "var(--color-text-primary)" : "var(--color-text-tertiary)",
              }}>{t.label}</button>
            ))}
          </div>
          <pre style={{
            flex: 1, margin: 0, padding: 12, fontSize: 12, lineHeight: 1.6, overflow: "auto",
            background: "var(--color-background-secondary)", border: "0.5px solid var(--color-border-tertiary)",
            borderRadius: "var(--border-radius-md)", color: "var(--color-text-primary)", whiteSpace: "pre-wrap",
            minHeight: 340,
          }}>
            {result ? activeOutput : "// Waiting for valid manifest..."}
          </pre>
        </div>
      </div>

      {/* Stats bar */}
      {result && (
        <div style={{ display: "flex", gap: 16, marginTop: 12, padding: "8px 12px", background: "var(--color-background-secondary)", borderRadius: "var(--border-radius-md)", fontSize: 12, color: "var(--color-text-secondary)", flexWrap: "wrap", alignItems: "center" }}>
          <span>Training bots blocked: <span style={{ fontWeight: 500, color: result.stats.trainingBlocked > 0 ? "var(--color-text-danger)" : "var(--color-text-success)" }}>{result.stats.trainingBlocked}/{TRAINING_BOTS.length}</span></span>
          <span>AI-input bots blocked: <span style={{ fontWeight: 500, color: result.stats.aiInputBlocked > 0 ? "var(--color-text-danger)" : "var(--color-text-success)" }}>{result.stats.aiInputBlocked}/{AI_INPUT_BOTS.length}</span></span>
          <span>AIPREF header: <span style={{ fontWeight: 500 }}>{result.aipref.startsWith("#") ? "none" : result.aipref.replace("Content-Usage: ", "")}</span></span>
          <span>Output lines: <span style={{ fontWeight: 500 }}>{lineCount}</span></span>
          {result.issues.length > 0 && (
            <span style={{ color: "var(--color-text-warning)" }}>
              {result.issues.length} warning{result.issues.length > 1 ? "s" : ""}: {result.issues[0]}
            </span>
          )}
        </div>
      )}
    </div>
  );
}
